services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db-gobelin:/var/lib/postgresql/data
    networks:
      - backend

  liquibase:
    image: liquibase/liquibase:4.23
    container_name: liquibase
    restart: on-failure:5
    environment:
      LIQUIBASE_COMMAND_URL: ${DATABASE_URL}?user=${POSTGRES_USER}&password=${POSTGRES_PASSWORD}
      LIQUIBASE_COMMAND_CHANGELOG_FILE: changelog/changelog-master.xml
    volumes:
      - ./db/migrations/:/liquibase/changelog
    depends_on:
      - db
    entrypoint: ["sh", "-c", "liquibase update || echo 'Migration failed, retrying...'"]
    networks:
      - backend
  
  db-access:
    build:
      context: ./db-access
      dockerfile: Dockerfile.prod
    image: gobelin-db-access:${VERSION}
    container_name: db-access
    restart: always
    depends_on:
      - db
      - liquibase
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - backend
    entrypoint: python
    command: -m src.main.main

  data-pipeline:
    build:
      context: ./data-pipeline
      dockerfile: Dockerfile.prod
    image: gobelin-data-pipeline:${VERSION}
    container_name: data-pipeline
    restart: always
    depends_on:
      - db
      - liquibase
    environment:
      DATABASE_URL: ${DATABASE_URL}
      LOG_LEVEL: ${LOG_LEVEL}
    networks:
      - backend
    entrypoint: python
    command: -m src.main.main

volumes:
  db-gobelin:

networks:
  backend:
    driver: bridge