# Fundamental image
FROM python:3.10-slim

# Configuration
WORKDIR /db-access
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Dependancies installation
COPY requirements.txt /db-access/requirements.txt
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy sources
COPY /db-access/src/ /db-access/src
COPY /db-access/config/ /db-access/config